# This manifest written by Jolene Engo <dev.toaster@gmail.com>
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
        - name: replicaCount
          value: '6' 
    repoURL: https://charts.jetstack.io
    targetRevision: v1.12.1
  syncPolicy:
    automated: {}
      # prune: false
      # selfHeal: true
    syncOptions:
      - CreateNamespace=true
