apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: git-argo
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8080
      nodePort: 30001
  selector:
    app: jenkins

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins
